server:
  port: 8084

spring:
  application:
    name: auth-service


jwt:
  secret: super-secreto-1234567890-mas-seguro-2025
  expiration-ms: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
