version: '3.8'

services:
  # ------------------- Eureka Server -------------------
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - library-net

  # ------------------- PostgreSQL for User Service -------------------
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - library-net
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

  # ------------------- User Service -------------------
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - eureka-server
      - postgres-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - library-net

  # ------------------- PostgreSQL for Book Service -------------------
  postgres-book:
    image: postgres:15-alpine
    container_name: postgres-book
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - library-net
    volumes:
      - postgres-book-data:/var/lib/postgresql/data

  # ------------------- Book Service -------------------
  book-service:
    build:
      context: ./book-service
    container_name: book-service
    depends_on:
      - eureka-server
      - postgres-book
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-book:5432/booksdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - library-net

  # ------------------- PostgreSQL for Reservation Service -------------------
  postgres-reservation:
    image: postgres:15-alpine
    container_name: postgres-reservation
    environment:
      POSTGRES_DB: reservationsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - library-net
    volumes:
      - postgres-reservation-data:/var/lib/postgresql/data

  # ------------------- Reservation Service -------------------
  reservation-service:
    build:
      context: ./reservation-service
    container_name: reservation-service
    depends_on:
      - eureka-server
      - postgres-reservation
      - user-service
      - book-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-reservation:5432/reservationsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8083:8083"
    networks:
      - library-net

  # ------------------- API Gateway -------------------
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
      - user-service
      - book-service
      - reservation-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - library-net

# ------------------- Networks -------------------
networks:
  library-net:
    driver: bridge

# ------------------- Volumes -------------------
volumes:
  postgres-user-data:
  postgres-book-data:
  postgres-reservation-data:
