server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth Service - RUTAS PÚBLICAS (sin token)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # User Service - Rutas específicas PÚBLICAS para FeignClient (MÁS ESPECÍFICAS PRIMERO)
        - id: user-service-email
          uri: lb://user-service
          predicates:
            - Path=/users/email/**

        - id: user-service-validate
          uri: lb://user-service
          predicates:
            - Path=/users/validate
            - Method=POST

        - id: user-service-create
          uri: lb://user-service
          predicates:
            - Path=/users
            - Method=POST

        # User Service - RUTAS PROTEGIDAS (requieren token)
        - id: user-service-protected
          uri: lb://user-service
          predicates:
            - Path=/api/users,/api/users/**
          filters:
            - RewritePath=/api/users(?<segment>.*), /users${segment}

        # Book Service - RUTAS PROTEGIDAS (requieren token)
        - id: book-service-protected
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
          filters:
            - RewritePath=/api/books/(?<segment>.*), /books/${segment}

      # Configuración CORS global
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - Content-Type

# Configuración JWT - MISMA CLAVE QUE AUTH-SERVICE
jwt:
  secret: super-secreto-1234567890-mas-seguro-2025

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Configuración de logging para debug
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.example.api_gateway: DEBUG
    org.springframework.security: INFO