server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # El servidor no se registra a sí mismo
    fetch-registry: false        # No busca otros servicios
  server:
    enable-self-preservation: false  # Para desarrollo, deshabilita autopreservación

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Para ver estado desde /actuator
